// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/results': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/results/index.get').default>>>>
    }
    '/api/test/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test/config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test/config.post').default>>>>
    }
    '/api/test/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test/start.post').default>>>>
    }
    '/api/test/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test/submit.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}